# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do 
  desc("Run all tests")
  lane :test do 
    gradle(task: "test")
  end 

  lane :release do 
    desc("Sign, build and release")
    
    gradle(
      task: "bundle",
      flavor: "production",
      build_type: "release"
    )
    
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      release_status: 'completed',
      track: 'draft'
    )
  end
end
