# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

plugins = [ 
  'fastlane-plugin-firebase_app_distribution'
]

default_platform(:android)

platform :android do 
  desc("Run all tests")
  lane :test do 
    gradle(task: "test")
  end 

  lane :production do 
    desc("Sign, build and release to production")
    
    gradle(
      task: "bundle",
      flavor: "production",
      build_type: "release"
    )
    
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      release_status: 'completed',
      track: 'production',
      json_key: '.sonin/production_playstore_api_key.json'
    )
  end

  lane :uat do
    desc("Sign, build and release to uat")

    gradle(
      task: "bundle",
      flavor: "uat",
      build_type: "release"
    )

    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      release_status: 'completed',
      track: 'internal',
      json_key: '.sonin/uat_playstore_api_key.json'
    )
  end

  lane :staging do
    desc("Sign, build and release to staging")

    gradle(
      task: "bundle",
      flavor: "staging",
      build_type: "release"
    )
    
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_screenshots: true,
      release_status: 'completed',
      track: 'internal',
      json_key: '.sonin/staging_playstore_api_key.json'
    )
  end

  lane :staging-firebase do 
    desc("Sign, build and release to staging")
    
    gradle(
      task: "bundle",
      flavor: "staging",
      build_type: "release"
    )

    firebase_app_distribution(
      app: "1:162819568560:android:42b2b5e9f6a7e610865c75",
      testers: "james.young@sonin.agency",
      release_notes: "They're around here somewhere...",
      android_artifact_type: "AAB"
    )
  end 
end
