name: Production release

on:
  push:
    branches:
      - production

env:
  SONIN_KEYS_PASSPHRASE: ${{ secrets.SONIN_KEYS_PASSPHRASE }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Log env variables
      run: echo $SONIN_KEYS_PASSPHRASE

    - name: Install fastlane
      run: |
        sudo apt-get update && sudo apt-get install ruby
        sudo gem install fastlane -NV

    - name: Decrypt Sonin secrets
      run: sh ./scripts/decrypt_secret.sh
      
    - name: Build and Release Android App
      run: fastlane android release
      working-directory: android

