name: Production release

on:
  push:
    branches:
      - production

env:
  SONIN_KEYS_PASSPHRASE: ${{ secrets.SONIN_KEYS_PASSPHRASE }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Bundler and Fastlane
      run: |
        gem install bundler
        bundle install

    - name: Decrypt Sonin secrets
      run: sh ./scripts/decrypt_secret.sh
      
    - name: Build and Release Android App
      run: fastlane android release
      working-directory: ./
